Hrbe 51
hirecoderdev/backend_restructure pull request #1
Opened 2023-10-06 13:59 UTC by Vasantgoudapatil

Registration

2023-10-06 14:02 UTC, Abishek05 commented on Pipfile
> +[dev-packages]
Shouldn't this file be not pushed? Please add to it.gitignore

2023-10-06 14:06 UTC, Abishek05 commented on accounts/user_manager.py
> +
This file is not required

2023-10-06 14:07 UTC, Abishek05 commented on accounts/serializers.py
> +        ]
Agency was not asked as per the ticket

2023-10-06 14:07 UTC, Abishek05 commented on accounts/models.py
> +    id = models.UUIDField(primary_key=True,default=uuid.uuid4, editable=False, unique=True)
Rever back to AbstractUser

2023-10-06 14:08 UTC, Abishek05 commented on accounts/models.py
> +    id = models.UUIDField(primary_key=True,default=uuid.uuid4, editable=False, unique=True)
Same here, agency is out of scope of this ticket

2023-10-06 14:08 UTC, Abishek05 commented on accounts/models.py
> +from .user_manager import UserManager
Writing own UserManager is unnecessary

2023-10-06 14:09 UTC, Abishek05 commented on accounts/migrations/0001_initial.py
> +                        ],
Do not edit the migrations file as it is not meant to be edited

2023-10-06 14:10 UTC, Abishek05 commented on accounts/views.py
> +        return Response(user_data,status=status.HTTP_201_CREATED)
Use ModelViewset and not GenericAPIView

2023-10-06 14:11 UTC, Abishek05 commented on mysite/urls.py
> +    path('api/', include('accounts.urls')),
Add routers

2023-10-06 14:12 UTC, Abishek05 requested changes
Changes to be made, many things are worked on are out of scope of the ticket

2023-10-11 13:51 UTC, Abishek05 commented on accounts/models.py
> +    )
As discussed, this line of code needs to be reverted

2023-10-11 13:53 UTC, Abishek05 commented on accounts/models.py
> -    middle_name = models.CharField(max_length=150)
middle_name is required

2023-10-11 13:54 UTC, Abishek05 commented on accounts/models.py
> +    is_profile_complete = models.BooleanField(default=False)
This is out of scope of this ticket, please remove `is_profile_complete` field

2023-10-11 13:56 UTC, Abishek05 commented on accounts/models.py
> +        super().save(*args, **kwargs)
Instead of this, make `is_root_user` default to true

2023-10-11 14:08 UTC, Abishek05 commented on accounts/utils.py
> +            print(f"Email sending failed: {str(e)}")
Remove debug messages

2023-10-11 14:11 UTC, Abishek05 commented on accounts/views.py
> +
Do not use APIView as discussed earlier. This is out of Scope. Please remove or comment out for now

2023-10-11 14:15 UTC, Abishek05 commented on accounts/views.py
> +    def post(self, request):
post() will not work in ModelViewset, you need to overwrite create() method

2023-10-11 14:17 UTC, Abishek05 commented on accounts/views.py
> +        absurl = "http://" + current_site + relative_link + "?token=" + str(token)
use f strings here to presentation looks easier on the eyes

2023-10-11 14:23 UTC, Vasantgoudapatil commented on accounts/admin.py
> +admin.site.register(User, UserAdmin)
Ok will take that off

2023-10-11 14:23 UTC, Vasantgoudapatil commented on accounts/models.py
> -    middle_name = models.CharField(max_length=150)
ok

2023-10-11 14:23 UTC, Vasantgoudapatil commented on accounts/models.py
> +        super().save(*args, **kwargs)
ok

2023-10-11 14:24 UTC, Vasantgoudapatil commented on accounts/models.py
> +    is_profile_complete = models.BooleanField(default=False)
ok

2023-10-11 14:24 UTC, Vasantgoudapatil commented on accounts/utils.py
> +            print(f"Email sending failed: {str(e)}")
ok

2023-10-11 14:24 UTC, Vasantgoudapatil commented on accounts/views.py
> +
Ok will comment it out for now as it is required in another ticket

2023-10-12 18:56 UTC, Abishek05 approved these changes
LGTM

2023-10-12 18:56 UTC, merged