HRBE:56 - Created the views and serializers for login api
hirecoderdev/backend_restructure pull request #2
Opened 2023-10-06 14:51 UTC by deepak-jv

2023-10-06 15:15 UTC, Abishek05 commented on accounts/views.py
> +class LoginAPIView(generics.GenericAPIView):
use ModelViewset please

2023-10-06 15:16 UTC, Abishek05 commented on accounts/serializers.py
> +        if not user.is_verified:
This should be `is_email_verified` as per the User model

2023-10-06 15:16 UTC, Abishek05 commented on accounts/serializers.py
> +                detail='Please continue your login using ' + filtered_user_by_email[0].auth_provider)
use f string if possible

2023-10-09 20:16 UTC, deepak-jv commented on accounts/serializers.py
> +        max_length=255, min_length=3, read_only=True)
done

2023-10-09 20:16 UTC, deepak-jv commented on accounts/views.py
> +class LoginAPIView(generics.GenericAPIView):
done

2023-10-09 20:16 UTC, deepak-jv commented on accounts/serializers.py
> +        if not user.is_verified:
done

2023-10-09 20:16 UTC, deepak-jv commented on accounts/serializers.py
> +                detail='Please continue your login using ' + filtered_user_by_email[0].auth_provider)
done

2023-10-09 20:17 UTC, deepak-jv commented on accounts/views.py
> +        return Response(serializer.data, status=status.HTTP_200_OK)
done

2023-10-11 14:31 UTC, Abishek05 commented on accounts/serializers.py
> +                    raise serializers.ValidationError("User account is disabled.")
User account is disabled is used twice

2023-10-11 14:37 UTC, Abishek05 commented on accounts/views.py
> +        "post",
inclue "head" and "options"

2023-10-11 14:38 UTC, Abishek05 commented on accounts/views.py
> +    queryset = User.objects.all()
Queryset is not required as we are disabling "GET" method

2023-10-11 14:43 UTC, Abishek05 commented on accounts/serializers.py
> +class LoginSerializer(serializers.Serializer):
Use ModelSerializer and ```extra_kwargs = {
            'password': {
                'write_only': True,
                'style': {'input_type': 'password'}
            },
    
        }```
to make sure passsword is hidden in browsable API

2023-10-11 14:49 UTC, Abishek05 commented on accounts/views.py
> +        )
This logic , please put it in serilaizer overriding validate() method

2023-10-11 14:49 UTC, Abishek05 requested changes
Seems like your IDE has automatically replaced all single quotes with double. Make sure to disable such extensions else your PR will have lot of changes and difficult to review

2023-10-12 20:22 UTC, Abishek05 commented on mysite/urls.py
> +router.register(r"skill-dropdown", SkillViewSet, basename="skill")  # noqa: E501
remove `r`, it's not required

2023-10-12 20:26 UTC, deepak-jv commented on accounts/views.py
> +        )
done

2023-10-12 20:26 UTC, deepak-jv commented on accounts/serializers.py
> +class LoginSerializer(serializers.Serializer):
done

2023-10-12 20:26 UTC, deepak-jv commented on accounts/views.py
> +    queryset = User.objects.all()
done

2023-10-12 20:26 UTC, deepak-jv commented on accounts/serializers.py
> +                    raise serializers.ValidationError("User account is disabled.")
done

2023-10-12 20:26 UTC, deepak-jv commented on accounts/views.py
> +        "post",
done

2023-10-12 20:28 UTC, deepak-jv commented on mysite/urls.py
> +router.register(r"skill-dropdown", SkillViewSet, basename="skill")  # noqa: E501
done

2023-10-12 20:30 UTC, Abishek05 approved these changes
LGTM

2023-10-12 20:31 UTC, merged

2023-10-17 13:39 UTC, Abishek05 commented on accounts/models.py
> +
@deepak-jv Why was this added twice?

2023-10-17 13:44 UTC, Abishek05 commented on accounts/models.py
> +
We don't require to set these

2023-10-17 13:45 UTC, deepak-jv commented on accounts/models.py
> +
My PR and Vasant's PR both gets merged on the same day and I got the merge conflicts but the you we have to show the demo on Friday that's why I might miss this to remove.